[package]
name = "curved"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
itertools = "0.13.0"
tiff = "0.9.1"
image = "0.25.5"
imageproc = "0.25.0"
ab_glyph = "0.2.29"
splines = "4.4.1"
